### ISSUE TITLE
Count issue WireGaurd and pivpn -l

### ISSUE THREAD

**Issue by TonySac** [woodmj74/pivpn_vpnrpt#5]
First off, great job with this.  I stumbled upon it while working on my own similar project. 

I attached a screenshot of my output of "pivpn -l" showing a final row "::: Disabled Clients :::"  This resulted in a miscount and ":::" being included in the "deviceList".

<img width="669" alt="Screen Shot 2022-03-08 at 11 20 40 PM" src="https://user-images.githubusercontent.com/60989281/157392479-7810f6b3-af5b-4aef-bf48-7ab81f34d937.png">

I changed the deviceCount formula as follows to account for the additional 4 arguments:

`
#Initial formula
deviceCount = (len(rawDevices) - 9) / 7

#Updated formula
deviceCount = (len(rawDevices) - 13) / 7
`

**Comment by woodmj74** [comment]
Awesome - glad someone has made use of this. As mentioned at the front I very much hacked this together so pleased its worked for someone other than myself!

Good call on the count going out. I've not had it running for a while whilst being stuck at home so didn't spot it; but recently turned it back on ready for travelling again so glad you found it and helped me out :-)
